---
language: ruby
script: "bundle exec rake validate spec"
matrix:
  include:
  - rvm: 2.3.0
    env: MAIN_ENV='y' # Used to only run the release task once.
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION='3.1.0'
after_success: "bundle exec rake travis_release"
